/*
 * Order Service
 *
 * Services that provides the capabilities for orders and Odoo
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package order_api

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// CreateRangerOrderUsingPOST - createRangerOrder
func CreateRangerOrderUsingPOST(c *gin.Context) {
	
	c.JSON(http.StatusOK, gin.H{})
}
