/*
 * Demo
 *
 * This is the API descriptor for the Demo Server
 *
 * API version: 0.1.0
 * Contact: test@aaa.global
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	initialize "server/_init"
	api "server/server/api"
	conf "server/server/conf"

	"github.com/gin-gonic/gin"
)

func addRoutes(router *gin.Engine) {
	// endpoints
	order_group := router.Group("/order")
	{
		order_group.POST(
			"/v1/internal/ranger/create",
			api.CreateRangerOrderUsingPOST,
		)
	}

	odoo_group := router.Group("/order")
	{
		odoo_group.POST(
			"/ship/carrier",
			api.CreateShipUsingPOST,
		)
		odoo_group.GET(
			"/:storeId",
			api.OdooUsingGET,
		)
	}
}

func main() {
	log.Printf("Server Started")

	conf.InitProjectConfig()

	router := initialize.InitRouter(nil)

	addRoutes(router)

	// init server
	s := initialize.InitServer("localhost:9000", router)
	log.Fatal(s.ListenAndServe().Error())
}
