/*
 * Order Service
 *
 * Services that provides the capabilities for orders and Odoo
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package order

type Order struct {

	AddressId int32 `json:"addressId,omitempty"`

	AreaId int32 `json:"areaId,omitempty"`

	CampaignId int32 `json:"campaignId,omitempty"`

	CampaignTrackingData string `json:"campaignTrackingData,omitempty"`

	CancelUrl string `json:"cancelUrl,omitempty"`

	CartId string `json:"cartId,omitempty"`

	Comment string `json:"comment,omitempty"`

	CouponInstanceId int64 `json:"couponInstanceId,omitempty"`

	CreateTimestamp string `json:"createTimestamp,omitempty"`

	Currency string `json:"currency,omitempty"`

	CustomsClearanceType string `json:"customsClearanceType,omitempty"`

	DeclareUserName string `json:"declareUserName,omitempty"`

	DeliveryAddress string `json:"deliveryAddress,omitempty"`

	DeliveryCarrierId string `json:"deliveryCarrierId,omitempty"`

	DeliveryEmail string `json:"deliveryEmail,omitempty"`

	DeliveryExpressCompany string `json:"deliveryExpressCompany,omitempty"`

	DeliveryPhone string `json:"deliveryPhone,omitempty"`

	DeliveryPhoneCountryCode string `json:"deliveryPhoneCountryCode,omitempty"`

	DeliveryUserIdCard string `json:"deliveryUserIdCard,omitempty"`

	DeliveryUserName string `json:"deliveryUserName,omitempty"`

	DeliveryWaybillId string `json:"deliveryWaybillId,omitempty"`

	Discount int32 `json:"discount,omitempty"`

	DiscountCode string `json:"discountCode,omitempty"`

	Id string `json:"id,omitempty"`

	NotifyUrl string `json:"notifyUrl,omitempty"`

	OuterOrderId string `json:"outerOrderId,omitempty"`

	OuterUserId string `json:"outerUserId,omitempty"`

	PaidTimestamp string `json:"paidTimestamp,omitempty"`

	ParentOrderId string `json:"parentOrderId,omitempty"`

	Platform string `json:"platform,omitempty"`

	ProductTax int32 `json:"productTax,omitempty"`

	Products []ProductDto `json:"products,omitempty"`

	ShippingFee int32 `json:"shippingFee,omitempty"`

	ShippingTax int32 `json:"shippingTax,omitempty"`

	Status int32 `json:"status,omitempty"`

	StoreId string `json:"storeId,omitempty"`

	SuccessRedirectUrl string `json:"successRedirectUrl,omitempty"`

	Tax int32 `json:"tax,omitempty"`

	Total int32 `json:"total,omitempty"`

	TotalProductAmount int32 `json:"totalProductAmount,omitempty"`

	UpdateTimestamp string `json:"updateTimestamp,omitempty"`

	UserId string `json:"userId,omitempty"`
}
