/*
 * Order Service
 *
 * Services that provides the capabilities for orders and Odoo
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package order

type OdooCreateShipCommand struct {

	Dimension Dimension `json:"dimension,omitempty"`

	ExpressCompany string `json:"expressCompany,omitempty"`

	GrossWeight float64 `json:"grossWeight,omitempty"`

	Items []EnvoyItemDto `json:"items,omitempty"`

	MerchantOrderRef string `json:"merchantOrderRef,omitempty"`

	NetWeight float64 `json:"netWeight,omitempty"`

	OrderRef string `json:"orderRef,omitempty"`

	OrderTime string `json:"orderTime,omitempty"`

	SellerOrderRef string `json:"sellerOrderRef,omitempty"`

	TrackingReference string `json:"trackingReference,omitempty"`
}
