/*
 * Order Service
 *
 * Services that provides the capabilities for orders and Odoo
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package order

type LoadData struct {

	DeliverySlipUrl string `json:"deliverySlipUrl,omitempty"`

	DeliveryStatus string `json:"deliveryStatus,omitempty"`

	DomesticDeliveryCompany string `json:"domesticDeliveryCompany,omitempty"`

	TrackingReference string `json:"trackingReference,omitempty"`

	TrackingUrl string `json:"trackingUrl,omitempty"`

	WaybillId string `json:"waybillId,omitempty"`
}
