/*
 * Order Service
 *
 * Services that provides the capabilities for orders and Odoo
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package order

type RangerCreateOrderCommand struct {

	ClientOrderRef string `json:"clientOrderRef,omitempty"`

	ClientParentOrderRef string `json:"clientParentOrderRef,omitempty"`

	CreatedAt string `json:"createdAt,omitempty"`

	Currency string `json:"currency,omitempty"`

	Customer Customer `json:"customer,omitempty"`

	CustomerIdRef string `json:"customerIdRef,omitempty"`

	CustomsCode string `json:"customsCode,omitempty"`

	DeliveryWaybillError string `json:"deliveryWaybillError,omitempty"`

	DeliveryWaybillId string `json:"deliveryWaybillId,omitempty"`

	DistributorName string `json:"distributorName,omitempty"`

	ExpressCompany string `json:"expressCompany,omitempty"`

	ExpressType string `json:"expressType,omitempty"`

	IsDistributionOrder bool `json:"isDistributionOrder,omitempty"`

	IsSubOrder bool `json:"isSubOrder,omitempty"`

	Items []Item `json:"items,omitempty"`

	NonCashDeductionAmount float64 `json:"nonCashDeductionAmount,omitempty"`

	OrderType string `json:"orderType,omitempty"`

	PaidAt string `json:"paidAt,omitempty"`

	PayAmount float64 `json:"payAmount,omitempty"`

	PayId string `json:"payId,omitempty"`

	PayMerchantName string `json:"payMerchantName,omitempty"`

	PayMethod string `json:"payMethod,omitempty"`

	Payer Payer `json:"payer,omitempty"`

	PaymentPayId string `json:"paymentPayId,omitempty"`

	PlatformName string `json:"platformName,omitempty"`

	PlatformTransactionId string `json:"platformTransactionId,omitempty"`

	ShippingCost float64 `json:"shippingCost,omitempty"`

	ShippingTax float64 `json:"shippingTax,omitempty"`

	Status string `json:"status,omitempty"`

	StoreId string `json:"storeId,omitempty"`

	TotalTax float64 `json:"totalTax,omitempty"`

	UpdatedAt string `json:"updatedAt,omitempty"`
}
