/*
 * Order Service
 *
 * Services that provides the capabilities for orders and Odoo
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package order

type Product struct {

	Barcode string `json:"barcode,omitempty"`

	Brand string `json:"brand,omitempty"`

	Category map[string]interface{} `json:"category,omitempty"`

	CategoryId map[string]interface{} `json:"categoryId,omitempty"`

	Country map[string]interface{} `json:"country,omitempty"`

	CreatedAt map[string]interface{} `json:"createdAt,omitempty"`

	Currency string `json:"currency,omitempty"`

	Description map[string]interface{} `json:"description,omitempty"`

	Discount map[string]interface{} `json:"discount,omitempty"`

	ExpressType map[string]interface{} `json:"expressType,omitempty"`

	GrossWeight map[string]interface{} `json:"grossWeight,omitempty"`

	GroupBuyingPrice map[string]interface{} `json:"groupBuyingPrice,omitempty"`

	HsCode map[string]interface{} `json:"hsCode,omitempty"`

	Images map[string]interface{} `json:"images,omitempty"`

	Ingredient map[string]interface{} `json:"ingredient,omitempty"`

	IsOnsale map[string]interface{} `json:"isOnsale,omitempty"`

	LogisticsMode map[string]interface{} `json:"logisticsMode,omitempty"`

	MassUnit string `json:"massUnit,omitempty"`

	Model map[string]interface{} `json:"model,omitempty"`

	Name map[string]interface{} `json:"name,omitempty"`

	NameEn map[string]interface{} `json:"nameEn,omitempty"`

	NetWeight map[string]interface{} `json:"netWeight,omitempty"`

	PersonalPostalArticlesTax map[string]interface{} `json:"personalPostalArticlesTax,omitempty"`

	Price map[string]interface{} `json:"price,omitempty"`

	ProductId string `json:"productId,omitempty"`

	Rrp map[string]interface{} `json:"rrp,omitempty"`

	ShelfLife map[string]interface{} `json:"shelfLife,omitempty"`

	ShippingCost map[string]interface{} `json:"shippingCost,omitempty"`

	ShippingTime map[string]interface{} `json:"shippingTime,omitempty"`

	Skus []Sku `json:"skus,omitempty"`

	Spec map[string]interface{} `json:"spec,omitempty"`

	Status string `json:"status,omitempty"`

	StoreId map[string]interface{} `json:"storeId,omitempty"`

	TaxRate map[string]interface{} `json:"taxRate,omitempty"`

	TimeUnit map[string]interface{} `json:"timeUnit,omitempty"`

	UpdatedAt map[string]interface{} `json:"updatedAt,omitempty"`

	Vendor map[string]interface{} `json:"vendor,omitempty"`

	WarrantyPeriod int32 `json:"warrantyPeriod,omitempty"`
}
