/*
 * Order Service
 *
 * Services that provides the capabilities for orders and Odoo
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package order

type OdooOrderDto struct {

	ClientOrderRef string `json:"clientOrderRef,omitempty"`

	ClientParentOrderRef map[string]interface{} `json:"clientParentOrderRef,omitempty"`

	CreatedAt string `json:"createdAt,omitempty"`

	Currency string `json:"currency,omitempty"`

	Customer map[string]interface{} `json:"customer,omitempty"`

	CustomerIdRef map[string]interface{} `json:"customerIdRef,omitempty"`

	CustomerNote map[string]interface{} `json:"customerNote,omitempty"`

	CustomsCode string `json:"customsCode,omitempty"`

	CustomsFilingId map[string]interface{} `json:"customsFilingId,omitempty"`

	DeliverySlipUrl map[string]interface{} `json:"deliverySlipUrl,omitempty"`

	DestinationCode map[string]interface{} `json:"destinationCode,omitempty"`

	DistributorName map[string]interface{} `json:"distributorName,omitempty"`

	ExpressCompany map[string]interface{} `json:"expressCompany,omitempty"`

	ExpressType map[string]interface{} `json:"expressType,omitempty"`

	InsuranceFee map[string]interface{} `json:"insuranceFee,omitempty"`

	IsDistributionOrder bool `json:"isDistributionOrder,omitempty"`

	IsSubOrder bool `json:"isSubOrder,omitempty"`

	Items []Item `json:"items,omitempty"`

	NodeCode map[string]interface{} `json:"nodeCode,omitempty"`

	NonCashDeductionAmount map[string]interface{} `json:"nonCashDeductionAmount,omitempty"`

	OrderId map[string]interface{} `json:"orderId,omitempty"`

	OrderType string `json:"orderType,omitempty"`

	PaidAt map[string]interface{} `json:"paidAt,omitempty"`

	PayAmount float64 `json:"payAmount,omitempty"`

	PayCustomsNo map[string]interface{} `json:"payCustomsNo,omitempty"`

	PayId map[string]interface{} `json:"payId,omitempty"`

	PayMerchantName map[string]interface{} `json:"payMerchantName,omitempty"`

	PayMethod map[string]interface{} `json:"payMethod,omitempty"`

	Payer map[string]interface{} `json:"payer,omitempty"`

	PaymentPayId map[string]interface{} `json:"paymentPayId,omitempty"`

	PlatformName string `json:"platformName,omitempty"`

	PlatformTransactionId map[string]interface{} `json:"platformTransactionId,omitempty"`

	ProductsTotalTax float64 `json:"productsTotalTax,omitempty"`

	Seller map[string]interface{} `json:"seller,omitempty"`

	ShippingCost map[string]interface{} `json:"shippingCost,omitempty"`

	Status string `json:"status,omitempty"`

	TrackingReference map[string]interface{} `json:"trackingReference,omitempty"`

	UpdatedAt string `json:"updatedAt,omitempty"`
}
