/*
 * Order Service
 *
 * Services that provides the capabilities for orders and Odoo
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package order

type PilotResponse struct {

	Code int32 `json:"code,omitempty"`

	Data LoadData `json:"data,omitempty"`

	ErrorMessage string `json:"errorMessage,omitempty"`

	Message string `json:"message,omitempty"`
}
