/*
 * Order Service
 *
 * Services that provides the capabilities for orders and Odoo
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package order

type DataPayload struct {

	Orders []OdooOrderDto `json:"orders,omitempty"`
}
