/*
 * Order Service
 *
 * Services that provides the capabilities for orders and Odoo
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package order

type ProductDto struct {

	Barcode string `json:"barcode,omitempty"`

	Currency string `json:"currency,omitempty"`

	Discount int32 `json:"discount,omitempty"`

	ImageUrl string `json:"imageUrl,omitempty"`

	OuterProductId string `json:"outerProductId,omitempty"`

	OuterSkuId string `json:"outerSkuId,omitempty"`

	Price int32 `json:"price,omitempty"`

	ProductId string `json:"productId,omitempty"`

	ProductName string `json:"productName,omitempty"`

	Quantity int32 `json:"quantity,omitempty"`

	Rrp int32 `json:"rrp,omitempty"`

	SkuId string `json:"skuId,omitempty"`

	Spec string `json:"spec,omitempty"`

	Tax int32 `json:"tax,omitempty"`

	TaxRate float64 `json:"taxRate,omitempty"`
}
