/*
 * Order Service
 *
 * Services that provides the capabilities for orders and Odoo
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package order

type EnvoyItemDto struct {

	Barcode string `json:"barcode,omitempty"`

	Brand string `json:"brand,omitempty"`

	CountryOfOrigin string `json:"countryOfOrigin,omitempty"`

	CustomsFilingId string `json:"customsFilingId,omitempty"`

	CustomsUnitCode string `json:"customsUnitCode,omitempty"`

	CustomsUnitCodePackage string `json:"customsUnitCodePackage,omitempty"`

	CustomsUnitCodeWeight string `json:"customsUnitCodeWeight,omitempty"`

	DeclarationElements string `json:"declarationElements,omitempty"`

	GrossWeight float64 `json:"grossWeight,omitempty"`

	HsCode string `json:"hsCode,omitempty"`

	Ingredients string `json:"ingredients,omitempty"`

	Model string `json:"model,omitempty"`

	Name string `json:"name,omitempty"`

	NameCn string `json:"nameCn,omitempty"`

	NetWeight float64 `json:"netWeight,omitempty"`

	Price float64 `json:"price,omitempty"`

	Quantity int32 `json:"quantity,omitempty"`

	QuantityUom string `json:"quantityUom,omitempty"`

	SkuNumber string `json:"skuNumber,omitempty"`

	Spec string `json:"spec,omitempty"`

	Tax float64 `json:"tax,omitempty"`
}
