/*
 * Order Service
 *
 * Services that provides the capabilities for orders and Odoo
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package order

type Dimension struct {

	Height float64 `json:"height,omitempty"`

	Length float64 `json:"length,omitempty"`

	Weight float64 `json:"weight,omitempty"`

	Width float64 `json:"width,omitempty"`
}
