/*
 * Order Service
 *
 * Services that provides the capabilities for orders and Odoo
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package order

type Item struct {

	Discount map[string]interface{} `json:"discount,omitempty"`

	Price float64 `json:"price,omitempty"`

	Product Product `json:"product,omitempty"`

	Quantity int32 `json:"quantity,omitempty"`

	Tax map[string]interface{} `json:"tax,omitempty"`
}
