/*
 * Order Service
 *
 * Services that provides the capabilities for orders and Odoo
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package order

type Customer struct {

	Address1 string `json:"address1,omitempty"`

	Address2 string `json:"address2,omitempty"`

	City string `json:"city,omitempty"`

	Country string `json:"country,omitempty"`

	CountryCode string `json:"countryCode,omitempty"`

	Email string `json:"email,omitempty"`

	FirstName string `json:"firstName,omitempty"`

	LastName string `json:"lastName,omitempty"`

	Phone string `json:"phone,omitempty"`

	State string `json:"state,omitempty"`

	Zip string `json:"zip,omitempty"`
}
