/*
 * Order Service
 *
 * Services that provides the capabilities for orders and Odoo
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package order

type Payer struct {

	ChineseId string `json:"chineseId,omitempty"`

	Country string `json:"country,omitempty"`

	CountryCode string `json:"countryCode,omitempty"`

	FirstName string `json:"firstName,omitempty"`

	Tin string `json:"tin,omitempty"`
}
